//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBigBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hesap()
        {
            this.Odemeler = new HashSet<Odemeler>();
            this.ParaTransferleri = new HashSet<ParaTransferleri>();
        }
    
        public int hesapID { get; set; }
        public int musteriID { get; set; }
        public string hesapNo { get; set; }
        public Nullable<System.DateTime> acilmaZamani { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public int ekNo { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParaTransferleri> ParaTransferleri { get; set; }
    }
}
