//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBigBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParaTransferleri
    {
        public int TransferID { get; set; }
        public string aliciHesapNo { get; set; }
        public int gonderenHesapID { get; set; }
        public Nullable<decimal> miktar { get; set; }
        public Nullable<System.DateTime> gonderimTarihi { get; set; }
        public int islemID { get; set; }
    
        public virtual Hesap Hesap { get; set; }
        public virtual Islemler Islemler { get; set; }
    }
}
